from typing import Protocol


class GeographySource(Protocol):
    def boundaries(self) -> dict: ...
    def weather(self, latitude, longitude, start, end) -> tuple[dict, dict]: ...
    def provenance(self) -> list[str]: ...


class ResearchFiles(Protocol):
    def write_json(self, name, value) -> None: ...
    def write_frame(self, name, frame) -> None: ...
    def hashes(self, names) -> dict: ...


class ResearchInput(Protocol):
    def read_frame(self, path, **options): ...
    def read_firms(self, path) -> list[dict]: ...
    def digest(self, path) -> str: ...


class Clock(Protocol):
    def now(self) -> str: ...


class ExperimentModel(Protocol):
    def fit_predict(self, train, test, features): ...
    def evaluate(self, actual, predicted, score) -> dict: ...
    def versions(self) -> dict: ...
